# ============================================================
# POST-PROCESSING SCRIPT FOR TRAINING OUTPUTS (SEPARATE BY MODEL)
#
# Purpose:
#   1. Load already saved .npy files generated by the TRAINING scripts.
#   2. Keep each algorithm's post-processed training graphs separate.
#   3. For each algorithm, plot ONLY:
#        - the algorithm result
#        - its baseline
#   4. Add SINR quality threshold lines:
#        Poor       < 0 dB
#        Fair       >= 0 and < 13 dB
#        Good       >= 13 and < 20 dB
#        Excellent  >= 20 dB
#   5. Convert energy consumption and energy efficiency to percentages
#      relative to baseline.
#
# This script does NOT rerun ns-3.
# This script does NOT reload trained models.
#
# Expected training output folders:
#   ddqn_per_results_c_5_500_2/
#   ppo_results_4_500_5/
#   qlearning_results_c_10_500_2/
#
# Output structure:
#   ddqn_per_results_c_5_500_2/postprocessed_percent_thresholds/
#   ppo_results_4_500_5/postprocessed_percent_thresholds/
#   qlearning_results_c_10_500_2/postprocessed_percent_thresholds/
# ============================================================

import argparse
import csv
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# 1. CONFIGURATION
# ============================================================
MODELS = {
    "DDQN": "ddqn_per_results_c_5_500_2",
    "PPO": "ppo_results_4_500_5",
    "Q-Learning": "qlearning_results_c_10_500_2",
}

OUTPUT_SUBDIR = "postprocessed_percent_thresholds"

NUM_UES = 30
SIM_TIME = 10
PACKET_INTERVAL = 0.02778
PACKET_SIZE_BYTES = 1400

# Dark magenta so it is clearly different from blue, orange, green, red.
THRESHOLD_COLOR = "#8B008B"

SINR_THRESHOLDS = {
    "Poor/Fair": 0.0,
    "Fair/Good": 13.0,
    "Good/Excellent": 20.0,
}

SINR_BANDS = [
    ("Poor", -50.0, 0.0),
    ("Fair", 0.0, 13.0),
    ("Good", 13.0, 20.0),
    ("Excellent", 20.0, 50.0),
]


# ============================================================
# 2. HELPERS
# ============================================================
def get_total_bits():
    packets_per_ue = SIM_TIME / PACKET_INTERVAL
    total_packets = packets_per_ue * NUM_UES
    return total_packets * PACKET_SIZE_BYTES * 8


def load_first_existing(folder, candidate_filenames, required=True):
    folder = Path(folder)

    for filename in candidate_filenames:
        path = folder / filename
        if path.exists():
            print(f"  Loaded: {path}")
            return np.asarray(np.load(path, allow_pickle=True), dtype=np.float64), path

    if required:
        raise FileNotFoundError(
            f"Could not find any of these files in {folder}:\n"
            + "\n".join([f"  - {name}" for name in candidate_filenames])
        )

    return None, None


def trim_to_same_length(*arrays):
    valid_arrays = [arr for arr in arrays if arr is not None]
    min_len = min(len(arr) for arr in valid_arrays)
    return [arr[:min_len] if arr is not None else None for arr in arrays]


def safe_percentage(numerator, denominator):
    numerator = np.asarray(numerator, dtype=np.float64)
    denominator = np.asarray(denominator, dtype=np.float64)

    return np.divide(
        numerator,
        denominator,
        out=np.zeros_like(numerator, dtype=np.float64),
        where=np.abs(denominator) > 1e-12,
    ) * 100.0


def compute_efficiency_from_energy(energy):
    total_bits = get_total_bits()
    energy = np.asarray(energy, dtype=np.float64)
    return np.divide(
        total_bits,
        energy,
        out=np.zeros_like(energy, dtype=np.float64),
        where=energy > 0,
    )


def add_sinr_thresholds(ax, x_max):
    for _label, value in SINR_THRESHOLDS.items():
        ax.axhline(
            y=value,
            linestyle="--",
            linewidth=1.5,
            color=THRESHOLD_COLOR,
        )
        ax.text(
            x_max + 0.3,
            value,
            f"{value:g} dB",
            va="center",
            fontsize=9,
            color=THRESHOLD_COLOR,
        )

    band_label_x = x_max + 0.8
    for band_name, y_min, y_max in SINR_BANDS:
        y_mid = (y_min + y_max) / 2.0
        if band_name == "Poor":
            y_mid = -2.0
        elif band_name == "Excellent":
            y_mid = 22.0

        ax.text(
            band_label_x,
            y_mid,
            band_name,
            va="center",
            fontsize=9,
            fontweight="bold",
            color=THRESHOLD_COLOR,
        )


# ============================================================
# 3. LOAD RESULTS FOR ONE MODEL
# ============================================================
def load_model_training_results(model_name, folder):
    print(f"\n>>> Loading training result files for {model_name} from: {folder}")

    rl_energy, _ = load_first_existing(
        folder,
        [
            "rl_energy_per_episode.npy",
            "energy_per_episode.npy",
            "trained_ddqn_per_agent_energy.npy",
            "trained_ppo_agent_energy.npy",
            "trained_q_agent_energy.npy",
        ],
        required=True,
    )

    baseline_energy, _ = load_first_existing(
        folder,
        [
            "baseline_energy_per_episode.npy",
            "baseline_energy.npy",
            "baseline_energy_qlearning.npy",
        ],
        required=True,
    )

    rl_sinr, _ = load_first_existing(
        folder,
        [
            "sinr_per_episode.npy",
            "rl_sinr_per_episode.npy",
            "trained_ddqn_per_agent_sinr.npy",
            "trained_ppo_agent_sinr.npy",
            "trained_q_agent_sinr.npy",
        ],
        required=True,
    )

    baseline_sinr, _ = load_first_existing(
        folder,
        [
            "baseline_sinr_per_episode.npy",
            "baseline_sinr.npy",
            "baseline_sinr_qlearning.npy",
        ],
        required=True,
    )

    rl_efficiency_existing, _ = load_first_existing(
        folder,
        [
            "energy_efficiency_per_episode.npy",
            "rl_energy_efficiency_per_episode.npy",
            "rl_efficiency_per_episode.npy",
        ],
        required=False,
    )

    baseline_efficiency_existing, _ = load_first_existing(
        folder,
        [
            "energy_efficiency_baseline.npy",
            "baseline_energy_efficiency_per_episode.npy",
            "baseline_efficiency_per_episode.npy",
        ],
        required=False,
    )

    rl_efficiency = (
        rl_efficiency_existing
        if rl_efficiency_existing is not None
        else compute_efficiency_from_energy(rl_energy)
    )

    baseline_efficiency = (
        baseline_efficiency_existing
        if baseline_efficiency_existing is not None
        else compute_efficiency_from_energy(baseline_energy)
    )

    (
        rl_energy,
        baseline_energy,
        rl_sinr,
        baseline_sinr,
        rl_efficiency,
        baseline_efficiency,
    ) = trim_to_same_length(
        rl_energy,
        baseline_energy,
        rl_sinr,
        baseline_sinr,
        rl_efficiency,
        baseline_efficiency,
    )

    return {
        "rl_energy": rl_energy,
        "baseline_energy": baseline_energy,
        "rl_sinr": rl_sinr,
        "baseline_sinr": baseline_sinr,
        "rl_efficiency": rl_efficiency,
        "baseline_efficiency": baseline_efficiency,
    }


# ============================================================
# 4. PLOTTING FOR ONE MODEL ONLY
# ============================================================
def plot_sinr(model_name, data, output_dir):
    n = len(data["rl_sinr"])
    x = np.arange(1, n + 1)

    plt.figure(figsize=(6.4, 4.8))
    ax = plt.gca()

    ax.plot(x, data["rl_sinr"], linewidth=2, label=model_name)
    ax.plot(x, data["baseline_sinr"], linestyle="--", linewidth=2, label="Baseline")

    add_sinr_thresholds(ax, n)

    ax.set_xlabel("Episode")
    ax.set_ylabel("Global SINR (dB)")
    # Use a consistent title across algorithms.
    ax.set_title("SINR comparison")
    ax.grid(True)
    ax.legend(loc="best")
    ax.set_xlim(1, n + 4)

    plt.tight_layout()
    plt.savefig(Path(output_dir) / "sinr_comparison.png", dpi=300)
    plt.close()


def plot_energy_percent(model_name, data, output_dir):
    n = len(data["rl_energy"])
    x = np.arange(1, n + 1)

    rl_energy_percent = safe_percentage(data["rl_energy"], data["baseline_energy"])
    baseline_energy_percent = safe_percentage(data["baseline_energy"], data["baseline_energy"])

    plt.figure(figsize=(6.4, 4.8))
    ax = plt.gca()

    ax.plot(x, rl_energy_percent, linewidth=2, label=model_name)
    ax.plot(x, baseline_energy_percent, linestyle="--", linewidth=2, label="Baseline")

    ax.set_xlabel("Episode")
    ax.set_ylabel("Energy consumption (% of baseline)")
    ax.set_title("Energy consumption comparison")
    ax.grid(True)
    ax.legend(loc="best")

    plt.tight_layout()
    plt.savefig(Path(output_dir) / "energy_consumption_percent.png", dpi=300)
    plt.close()


def plot_efficiency_percent(model_name, data, output_dir):
    n = len(data["rl_efficiency"])
    x = np.arange(1, n + 1)

    rl_eff_percent = safe_percentage(data["rl_efficiency"], data["baseline_efficiency"])
    baseline_eff_percent = safe_percentage(data["baseline_efficiency"], data["baseline_efficiency"])

    plt.figure(figsize=(6.4, 4.8))
    ax = plt.gca()

    ax.plot(x, rl_eff_percent, linewidth=2, label=model_name)
    ax.plot(x, baseline_eff_percent, linestyle="--", linewidth=2, label="Baseline")

    ax.set_xlabel("Episode")
    ax.set_ylabel("Energy efficiency (% of baseline)")
    ax.set_title("Energy efficiency comparison")
    ax.grid(True)
    ax.legend(loc="best")

    plt.tight_layout()
    plt.savefig(Path(output_dir) / "energy_efficiency_percent.png", dpi=300)
    plt.close()


# ============================================================
# 5. CSV SUMMARY FOR ONE MODEL
# ============================================================
def save_model_csv(model_name, data, output_dir):
    csv_path = Path(output_dir) / "percentage_summary.csv"

    energy_percent = safe_percentage(data["rl_energy"], data["baseline_energy"])
    efficiency_percent = safe_percentage(data["rl_efficiency"], data["baseline_efficiency"])

    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "model",
            "episode",
            "rl_energy",
            "baseline_energy",
            "energy_consumption_percent_of_baseline",
            "rl_energy_efficiency",
            "baseline_energy_efficiency",
            "energy_efficiency_percent_of_baseline",
            "rl_sinr",
            "baseline_sinr",
        ])

        for i in range(len(data["rl_energy"])):
            writer.writerow([
                model_name,
                i + 1,
                data["rl_energy"][i],
                data["baseline_energy"][i],
                energy_percent[i],
                data["rl_efficiency"][i],
                data["baseline_efficiency"][i],
                efficiency_percent[i],
                data["rl_sinr"][i],
                data["baseline_sinr"][i],
            ])


# ============================================================
# 6. MAIN
# ============================================================
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-subdir",
        default=OUTPUT_SUBDIR,
        help="Subfolder to create inside each algorithm result folder.",
    )
    args = parser.parse_args()

    print(">>> Creating separate post-processed graphs for each training result folder...")

    for model_name, folder in MODELS.items():
        data = load_model_training_results(model_name, folder)
        output_dir = Path(folder) / args.output_subdir
        output_dir.mkdir(parents=True, exist_ok=True)

        print(f"\n>>> Saving post-processed graphs for {model_name} to: {output_dir}")
        plot_sinr(model_name, data, output_dir)
        plot_energy_percent(model_name, data, output_dir)
        plot_efficiency_percent(model_name, data, output_dir)
        save_model_csv(model_name, data, output_dir)

        print("  Created files:")
        for path in sorted(output_dir.glob("*")):
            print(f"    - {path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
